---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Text and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: s{{ secrets.DOCKERHUB_USER }}
          password: s{{ secrets.DOCKERHUB_TOKEN}}
      - name: Chechout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"